name: Go Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy
      
    - name: Build
      run: go build -v ./...

    - name: Start server in background
      run: |
        PORT=8080 go run main.go &
        sleep 5  # Give the server time to start

    - name: Test routes
      run: |
        # Test root route
        curl -f http://localhost:8080/ || exit 1
        # Test admin route
        curl -f http://localhost:8080/admin || exit 1

    - name: Stop server
      run: pkill -f "main.go"